#!/usr/bin/env bash
# index.sh — regenerate ~/.hivesmith/brain/INDEX.md from filesystem state.
#
# Tiered output:
#   <!-- HOT -->   ≤ BRAIN_HOT_LINES (default 50): pinned + recently-used + high-confidence
#   <!-- ALL -->   ≤ BRAIN_ALL_LINES (default 2000): everything else, sorted by scope then date desc
#
# Usage:
#   index.sh [--dry-run]    # --dry-run: print to stdout, do not modify INDEX.md
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh disable=SC1091
. "$DIR/lib.sh"

DRY_RUN=0
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=1

brain_lazy_init

HOT_LINES="${BRAIN_HOT_LINES:-50}"
ALL_LINES="${BRAIN_ALL_LINES:-2000}"

PY="$(brain_yaml_py)"

# Walk every .md file under universal/, ecosystem/, user/, project/, unverified/.
# Emit one TSV line per entry: scope\tecosystem\trepo\tcreated\tconfidence\tslug\tapplies_to\trel_path
# Then format and split into HOT and ALL tiers.

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

while IFS= read -r -d '' f; do
    rel="${f#"$BRAIN_HOME"/}"
    # Skip the index files themselves.
    case "$rel" in
        INDEX.md|README.md|SCHEMA.md|.gitignore) continue ;;
        archive/*) continue ;;
    esac
    fm="$(python3 "$PY" read "$f" 2>/dev/null || true)"
    [ -z "$fm" ] && continue
    scope="$(printf '%s' "$fm" | awk -F= '$1=="scope"{print $2; exit}')"
    ecosystem="$(printf '%s' "$fm" | awk -F= '$1=="ecosystem"{print $2; exit}')"
    repo="$(printf '%s' "$fm" | awk -F= '$1=="repo"{print $2; exit}')"
    created="$(printf '%s' "$fm" | awk -F= '$1=="created"{print $2; exit}')"
    confidence="$(printf '%s' "$fm" | awk -F= '$1=="confidence"{print $2; exit}')"
    slug="$(printf '%s' "$fm" | awk -F= '$1=="slug"{print $2; exit}')"
    applies_to="$(printf '%s' "$fm" | awk -F= '$1=="applies_to"{print $2; exit}')"
    valid_until="$(printf '%s' "$fm" | awk -F= '$1=="valid_until"{print $2; exit}')"
    [ -z "$scope" ] && continue
    [ -z "$slug" ] && slug="$(basename "$f" .md)"
    printf '%s|%s|%s|%s|%s|%s|%s|%s|%s\n' \
        "$scope" "${ecosystem:-}" "${repo:-}" "${created:-}" "${confidence:-0.5}" \
        "$slug" "${applies_to:-}" "${valid_until:-}" "$rel" >> "$tmp"
done < <(find "$BRAIN_HOME" -type f -name '*.md' -print0)

# Format one entry into a markdown line for INDEX.md.
format_line() {
    local scope="$1" ecosystem="$2" repo="$3" created="$4" confidence="$5" slug="$6" applies_to="$7" valid_until="$8" rel="$9"
    local label="$scope"
    [ -n "$ecosystem" ] && label="$scope:$ecosystem"
    [ -n "$repo" ] && label="$scope:${repo:0:6}"
    local extras=""
    [ -n "$applies_to" ] && extras="$extras · applies_to=$applies_to"
    [ -n "$valid_until" ] && extras="$extras · valid_until=$valid_until"
    local link="${rel%.md}"
    printf -- '- [[%s]] · %s · conf=%s · %s%s\n' "$link" "$label" "$confidence" "$created" "$extras"
}

# Sort for the HOT tier: confidence desc, then created desc.
# LC_ALL=C: keep numeric sort independent of the user's locale (commas vs dots,
# etc.) so INDEX.md is byte-stable across environments.
hot_entries=""
if [ -s "$tmp" ]; then
    # shellcheck disable=SC2046
    hot_entries=$(LC_ALL=C sort -t'|' -k5,5gr -k4,4r "$tmp" | head -n "$HOT_LINES")
fi

# Sort for the ALL tier: scope asc, ecosystem asc, repo asc, created desc.
all_entries=""
if [ -s "$tmp" ]; then
    all_entries=$(LC_ALL=C sort -t'|' -k1,1 -k2,2 -k3,3 -k4,4r "$tmp" | head -n "$ALL_LINES")
fi

emit() {
    printf '<!-- generated by scripts/brain/index.sh — do not edit by hand -->\n\n'
    printf '<!-- HOT -->\n'
    if [ -n "$hot_entries" ]; then
        while IFS='|' read -r scope ecosystem repo created confidence slug applies_to valid_until rel; do
            format_line "$scope" "$ecosystem" "$repo" "$created" "$confidence" "$slug" "$applies_to" "$valid_until" "$rel"
        done <<< "$hot_entries"
    fi
    printf '<!-- HOT END -->\n\n'
    printf '<!-- ALL -->\n'
    if [ -n "$all_entries" ]; then
        while IFS='|' read -r scope ecosystem repo created confidence slug applies_to valid_until rel; do
            format_line "$scope" "$ecosystem" "$repo" "$created" "$confidence" "$slug" "$applies_to" "$valid_until" "$rel"
        done <<< "$all_entries"
    fi
    printf '<!-- ALL END -->\n'
}

out="$(emit)"

if (( DRY_RUN == 1 )); then
    printf '%s\n' "$out"
    exit 0
fi

target="$BRAIN_HOME/INDEX.md"
existing=""
[ -f "$target" ] && existing="$(cat "$target")"
if [ "$out" = "$existing" ]; then
    # Cache-friendly: don't touch if unchanged.
    exit 0
fi
printf '%s\n' "$out" > "$target"
git -C "$BRAIN_HOME" add INDEX.md >/dev/null 2>&1 || true
if ! git -C "$BRAIN_HOME" diff --cached --quiet 2>/dev/null; then
    git -C "$BRAIN_HOME" commit -q -m "brain: regenerate index" >/dev/null 2>&1 || true
fi
