name: Security

on:
  push:
    branches: [main]
  pull_request:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@e0c47f4f8be36e29cdc102c57e68cb5cbf0e8d1e  # v2 as of 2026-04-13
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: reviewdog/action-actionlint@6fb7acc99f4a1008869fa8a0f09cfca740837d9d  # v1 as of 2026-04-13
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
